name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"  # Executa todos os dias às 12:00 UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests (E2E)
      uses: cypress-io/github-action@v6
      with:
        record: false
        component: false

    - name: Run Performance Tests
      run: npx cypress run --spec "cypress/e2e/performance.cy.js"